module.exports = {
  username: "#username",
  password: "#password",
  loginButton: "input[class = 'btn-submit']",
  buildingLink: "li.wprm-building-link > a",
  roomLink: "a.room-link",
  roomName: "a.room-link > span",
  buildingName: ".entry-title",
  roomGrid: ".room-grid",
  roomInfo: "#classroom-info",
  roomContent: ".room-content",
  roomCapacity: ".capacity > span",
  roomType: ".type",
  roomFormat: ".format",
  roomTech: ".tech-details > ul > li",
  roomCarousel: ".carousel",
  roomImages: ".wprm-classroom-images-shown-images > img",
  termSelector: "div#s2id_txt_term",
  springTerm2019: "input#txt_term",
  termSearch: "button#select2-drop-mask"
};
